---
language: python
sudo: required
dist: xenial
python: "3.7"
cache: pip
install:
  - pip install -r requirements-dev.txt
script:
  - make lint
  - pip install .
  - make unittests
after_success: coveralls
